default: &default
  adapter: mysql2
  encoding: utf8mb4
  collation: utf8mb4_unicode_ci
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
  username: felipet_movies
  password: 123456
  host: localhost
  port: 3306

development:
  <<: *default
  database: minha_app_development

test:
  <<: *default
  database: minha_app_test

production:
  <<: *default
  database: minha_app_production
  username: <%= ENV["DB_USERNAME"] || "felipet_movies" %>
  password: <%= ENV["DB_PASSWORD"] || "123456" %>
  host: <%= ENV["DB_HOST"] || "localhost" %>
