default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: movies_db
  username: felipet_movies
  password: 123456


development:
  <<: *default
  database: movies_db


test:
  <<: *default
  database: movies_test
  username: postgres
  password:

production:
  <<: *default
  database: <%= ENV["DB_NAME"] %>
  username: <%= ENV["DB_USER"] %>
  password: <%= ENV["DB_PASSWORD"] %>
  host: <%= ENV["DB_HOST"] %>
  port: 5432
