local:
  service: Disk
  root: <%= Rails.root.join("storage") %>

amazon:
  service: S3
  access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] %>
  secret_access_key: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>
  region: "us-east-2"
  bucket: "movies-felipet"
  endpoint: "https://s3.us-east-2.amazonaws.com"
  force_path_style: false

